global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'kafka-exporter'
    static_configs:
      - targets: ['kafka-exporter:9308']
  - job_name: 'kafka-jmx-exporter'
    static_configs:
      - targets: ['kafka:7071']

  - job_name: 'spark-master'
    static_configs:
      - targets: ['spark:8085']
      
  - job_name: 'spark-worker'
    static_configs:
      - targets: ['spark-worker:8086']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
  
  - job_name: 'elasticsearch'
    metrics_path: '/_prometheus/metrics'
    static_configs:
      - targets: ['elasticsearch:9200']